// 环境变量配置
const ENV_CONFIG = {
  // 飞书应用凭证
  FEISHU_APP_ID: process.env.FEISHU_APP_ID || 'cli_a85bf6b4153bd013',
  FEISHU_APP_SECRET: process.env.FEISHU_APP_SECRET || 'AhOGT0tl2pkjXlynQ2Qb3gFXyXmbE2aP',
  
  // 表格访问配置
  FEISHU_APP_TOKEN: process.env.NEXT_PUBLIC_FEISHU_APP_TOKEN || 'R8XfbOXZ2a4fJjsWdpmc1rJOnbm',
  TABLE_BASE_DAILY: process.env.NEXT_PUBLIC_FEISHU_TABLE_BASE_DAILY || 'tbla2p0tHEBb6Xnj',
  TABLE_MONTH_SUMMARY: process.env.NEXT_PUBLIC_FEISHU_TABLE_MONTH_SUMMARY || 'tbl5hVlzM1gNVCT2',
  FEISHU_YEAR_PROFIT_TABLE_ID: process.env.NEXT_PUBLIC_FEISHU_YEAR_PROFIT_TABLE_ID || 'tbl2i7U6JZOeg6Rr', // 年度总利润表ID
  
  // Supabase 配置
  SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL || '',
  SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '',
  SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY || '',
};

// 调试信息
if (typeof window === 'undefined') {
  console.log('环境变量配置:', {
    FEISHU_APP_ID: ENV_CONFIG.FEISHU_APP_ID,
    FEISHU_APP_SECRET: ENV_CONFIG.FEISHU_APP_SECRET ? '已设置' : '未设置',
    FEISHU_APP_TOKEN: ENV_CONFIG.FEISHU_APP_TOKEN,
    TABLE_BASE_DAILY: ENV_CONFIG.TABLE_BASE_DAILY,
    TABLE_MONTH_SUMMARY: ENV_CONFIG.TABLE_MONTH_SUMMARY,
    FEISHU_YEAR_PROFIT_TABLE_ID: ENV_CONFIG.FEISHU_YEAR_PROFIT_TABLE_ID,
  });
}

export { ENV_CONFIG };
